# Generated by Django 4.0.3 on 2022-03-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio_father', to='contacts.contact')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio_mother', to='contacts.contact')),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('siblings', models.ManyToManyField(null=True, to='contacts.contact')),
            ],
        ),
    ]
