# Generated by Django 4.0.3 on 2022-03-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contact.person')),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband_and_wife', to='contact.person')),
                ('siblings', models.ManyToManyField(null=True, related_name='brother_and_sister', to='contact.person')),
            ],
        ),
    ]
