# Generated by Django 4.0.3 on 2022-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(related_name='brother_and_sister', to='contact.person'),
        ),
    ]
