# Generated by Django 4.0.3 on 2022-03-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_person_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(to='contact.person'),
        ),
    ]
