# Generated by Django 4.0.3 on 2022-03-12 06:39

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_person_siblings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_int', models.IntegerField(validators=[contact.models.int_is_even])),
            ],
        ),
    ]
