# Generated by Django 4.0.3 on 2022-03-12 08:07

import contact.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='even_int',
            field=contact.models.EventInteger(),
        ),
    ]
