# Generated by Django 4.0.3 on 2022-03-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='hi', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100, verbose_name='Your last name'),
        ),
    ]
