# Generated by Django 4.0.3 on 2022-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0003_remove_user_id_user_email_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
