# Generated by Django 4.0.3 on 2022-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(null=True)),
                ('str_value', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
